# Open Peer Review 

## Article
An, A.Y. et al. (2023) Dynamic gene expression analysis reveals distinct severity phases of immune and cellular dysregulation in COVID-19, bioRxiv. Available at: https://www.biorxiv.org/content/10.1101/2023.11.04.565404v1.full (Accessed: 02 May 2024). 

## Summary
Objective 
To investigate longitudinal changes in gene expression profiles throughout the COVID-19 disease timeline.

Methods 
Three-hundred whole blood samples from 128 adult patients were collected during hospitalization from COVID-19, with up to five samples per patient. Transcriptome sequencing (RNA-Seq), differential gene expression analysis and pathway enrichment was performed. Drug-gene set enrichment analysis was used to identify FDA-approved medications that could inhibit critical genes and proteins at each disease phase. Prognostic gene-expression signatures were generated using machine learning to distinguish 3 disease stages.

Results 
Samples were longitudinally grouped by clinical criteria and gene expression into six disease phases: Mild, Moderate, Severe, Critical, Recovery, and Discharge. Distinct mechanisms with differing trajectories during COVID-19 hospitalization were apparent. Antiviral responses peaked early in COVID-19, while heme metabolism pathways became active much later during disease. Adaptive immune dysfunction, inflammation, and metabolic derangements were most pronounced during phases with higher disease severity, while hemostatic abnormalities were elevated early and persisted throughout the disease course. Drug-gene set enrichment analysis predicted repurposed medications for potential use, including platelet inhibitors in early disease, antidiabetic medications for patients with increased disease severity, and dasatinib throughout the disease course. Disease phases could be categorized using specific gene signatures for prognosis and treatment selection. Disease phases were also highly correlated to previously developed sepsis endotypes, indicating that severity and disease timing were significant contributors to heterogeneity observed in sepsis and COVID-19.

Conclusions 
Higher temporal resolution of longitudinal mechanisms in COVID-19 revealed multiple immune and cellular changes that were activated at different phases of COVID-19. Understanding how a patient’s gene expression profile changes over time can permit more accurate risk stratification of patients and provide time-dependent personalized treatments with repurposed medications. This creates an opportunity for timely intervention before patients transition to a more severe phase, potentially accelerating patients to recovery.


## Review 
The article has been evaluated according to the criteria listed in the table below.


|    Transparency Criteria    	|                                                                                                                                Definition                                                                                                                                	|                                                                             Response                                                                            	|   	|   	|
|:---------------------------:	|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:	|:---------------------------------------------------------------------------------------------------------------------------------------------------------------:	|---	|---	|
| Study Purpose               	| A concise statement in the introduction of the article, often in the last paragraph, that establishes the reason the research was conducted. Also called the study objective.                                                                                            	| yes                                                                                                                                                             	|   	|   	|
| Data Availability Statement 	| A statement, in an individual section offset from the main body of text, that explains how or if one can access a study’s data. The title of the section may vary, but it must explicitly mention data; it is therefore distinct from a supplementary materials section. 	| yes                                                                                                                                                             	|   	|   	|
| Data Location               	| Where the article’s data can be accessed, either raw or processed.                                                                                                                                                                                                       	| The datasets generated for this study can be found on GEO: GSE221234 and GSE222253. Code is available upon request (Dr. Robert Hancock, bob{at}hancocklab.com). 	|   	|   	|
| Study Location              	| Author has stated in the methods section where the study took place or the data’s country/region of origin.                                                                                                                                                              	| yes,                                                                                                                                                            	|   	|   	|
| Author Review               	| The professionalism of the contact information that the author has provided in the manuscript.                                                                                                                                                                           	| yes, with information of the researchers and an e-mail.                                                                                                         	|   	|   	|
| Ethics Statement            	| A statement within the manuscript indicating any ethical concerns, including the presence of sensitive data.                                                                                                                                                             	| yes                                                                                                                                                             	|   	|   	|
| Funding Statement           	| A statement within the manuscript indicating whether or not the authors received funding for their research.                                                                                                                                                             	| yes                                                                                                                                                             	|   	|   	|
| Code Availability           	| Authors have shared access to the most updated code that they used in their study, including code used for analysis.                                                                                                                                                     	| no                                                                                                                                                              	|   	|   	|
